# Site
repository: BartJoris/bartjoris.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bart Joris
title: Solution Architect
email: mail@bartjoris.be
website: www.bartjoris.be

# Dark Mode (true/false/never)
darkmode: true

# Social links

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: bart-joris-8b669a61
# twitter_username: Bart_Joris
# github_username:  BartJoris
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bart, and my role as an <mark>Solution Architect</mark> involves working closely with customers to understand their business requirements and provide them with the best possible solution. I am responsible for analyzing their data, assessing their infrastructure, and collaborating with various stakeholders to ensure that the proposed solution is feasible, cost-effective, and meets the customer's expectations. My ultimate goal is to optimize their business processes, improve their bottom line, and enhance their overall customer experience.


content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Red Hat
        link: redhat.com
        sub_title: Solution Architect
        caption: September 2022 - Present
        # quote: >
        #   Providing engineers with a solid and easy to use infrastructure platform
        description: | # this will include new lines to allow paragraphs
            As an Account Solution Architect, I am passionate about delivering effective solutions to help businesses achieve their goals. I enjoy the challenge of analyzing complex data and finding innovative ways to optimize business processes. Collaboration is at the heart of my work, and I pride myself on building strong relationships with customers and stakeholders to ensure that the solutions we provide are aligned with their needs. The fast-paced nature of the role keeps me on my toes, and I thrive in an environment where I can use my technical and analytical skills to make a real difference to our customers' businesses.
      - layout: left
        title: Aaqua
        link: aaqua.live
        # link_text: boringcompany.com
        sub_title: Cloud engineer
        caption: May 2021 - August 2022
        # quote: >
        #   Providing engineers with a solid and easy to use infrastructure platform
        description: | # this will include new lines to allow paragraphs
            Providing engineers with a solid and easy-to-use infrastructure platform that supports business objectives. Their primary role involves designing, building, and maintaining cloud-based infrastructure solutions that are scalable and secure. This involves creating systems that can handle high traffic volumes and optimizing cloud-based applications for maximum efficiency. 
      - layout: left
        title: Nubera
        link: nubera.eu
        # link_text: boringcompany.com
        sub_title: Senior Cloud integration consultant
        caption: February 2016 - May 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Architectural design and implementation of container platforms on several cloud environments.
            Monitoring and automatic creation of virtual machines and containers with Terraform, Ansible, Gitlab CI/CD.
      - layout: left
        title: University Ghent
        link: ugent.be
        # link_text: boringcompany.com
        sub_title: System administrator
        caption: February 2014 - February 2016
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Implementation of an IaaS platform OpenStack.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HoGent
        caption: 2010 - 2014
        sub_title: Bachelor Applied Informatics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
